server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/v1/member-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<version>.*)/member-service/(?<path>.*),/$\{version}/$\{path}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/v1/member-service/members
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<version>.*)/member-service/(?<path>.*),/$\{version}/$\{path}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/v1/member-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<version>.*)/member-service/(?<path>.*),/$\{version}/$\{path}
            - AuthorizationHeaderFilter
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<path>.*),/$\{path}
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
      default-filters:
        - name : GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, refresh, health, beans, httptrace

